<?php 
$item_input='
<div> 
	<table class="dim" style="display:none;width:100%;">
		<tr>
			<th>'.$this->t->_('POSITION').'</th>
			<th>'.$this->t->_('DIMENTION').'</th>
		</tr>
		<tr>
			<td>x <input name="posx[]" class="posx" type="number" min="0" value="0" size="4" maxlength="4" style="width:50px;">px</td>
			<td>x <input name="dimx[]" class="dimx" type="number" min="32" value="100" size="4" maxlength="4" style="width:50px;">px</td>
		</tr>
		<tr>
			<td>y <input name="posy[]" class="posy" type="number" min="0" value="0" size="4" maxlength="4" style="width:50px;">px</td>
			<td>y <input name="dimy[]" class="dimy" type="number" min="32" value="100" size="4" maxlength="4" style="width:50px;">px</td>
		</tr>
	</table>
	<div class="delay" style="display:none">
		delay <input name="delay[]" class="delay" type="number" min="10" value="100" size="4" maxlength="4" style="width:50px;">cs
	<div>
</div>';
$this->headScript()->captureStart();?>
function checkform() {
return false;
}
function submit() {//<!--
	framedelay=$('#framebox input.delay');
	if (framedelay.length<2) {$('<div title="Error"><?php echo $this->t->_('TWOPICS');?></div>').dialog({ buttons: [
    {
        text: "Ok",
        click: function() { $(this).dialog("close"); }
    }
] });return false;}
	input=$('.form input:not([type=checkbox],[type=radio])');
	post={type:"frame"};
	
	framename=$('#framebox h4');
	dimx=$('#framebox .dimx');
	dimy=$('#framebox .dimy');
	post.delay=new Array();
	post.name=new Array();
	post.dimx=new Array();
	post.dimy=new Array();
	for(i=0;i<framedelay.length;i++) {
		post.delay.push(framedelay.eq(i).val());
		post.name.push(framename.eq(i).text());
		post.dimx.push(dimx.eq(i).val());
		post.dimy.push(dimy.eq(i).val());
	}//-->
	for(var key in input) {
		name=input.eq(key).attr('name');
		post[name]=input.eq(key).val();
	}
	post.delayTot=$('input[name=delayTot]').attr('checked');
	post.prop=$('input[name=prop]').attr('checked');
	post.dimT=$('input[name=dimT]').attr('checked');
	post.frameadd=$('input[name=frameadd]:checked').val();
	$.ajax({
		url: '<?php echo $this->url(array('controller'=>'make','action'=>'index'));?>',
		type: 'post',
		data: post,
		success:function(data) {
			$('<div><img src="<?php echo $this->baseUrl('/upload/'.$this->user);?>/prew.gif"></div>').dialog({
				close:function(event,ui){$(this).dialog( "destroy" );}
			});
		}
	});
}
function checkshow() {
	delay=$('ul#framebox div.delay');
	dim=$('ul#framebox .dim');
	if ($('input[name=dimT]').attr('checked')) {dim.hide();} else {dim.show();}
	if ($('input[name=delayTot]').attr('checked')) delay.hide(); else delay.show();
	$('ul#files (div.delay,.dim)').hide();
}
$(function(){
		var btnUpload=$('#upload');
		var status=$('#status');
		new AjaxUpload(btnUpload, {
			action: '<?php echo $this->url(array('controller'=>'uploader','action'=>'index'));?>',
			name: 'uploadfile',
			onSubmit: function(file, ext){
				 if (! (ext && /^(jpg|png|jpeg|gif)$/.test(ext))){ 
                    // extension is not allowed 
					status.text('Only JPG, PNG or GIF files are allowed');
					return false;
				}
				status.text('Uploading...');
			},
			onComplete: function(file, response){
				//On completion clear the status
				status.text('');
				//Add uploaded file to list
				if(response=="true"){
					$('<li></li>').appendTo('#files').html('<h4>'+file+'</h4><img src="<?php echo $this->baseUrl('upload/'.$this->user);?>/thumb'+file+'" alt="'+file+'" /><?php echo str_replace("\n", ' ', $item_input);?>').addClass('success');
				} else{
					$('<li></li>').appendTo('#files').text(file+'<div>'+response+'</div>').addClass('error');
					
				}
			}
		});
		$('.files').sortable({connectWith: "ul",items:"li:not(.listtitle)",stop:function(){
			checkshow();
			file=$('#trash h4').text();
			$('#trash li').remove();
			$.ajax({
				url : '<?php echo $this->url(array('controller'=>'delete','action'=>'index'));?>',
				type: 'post',
				data : {'file':file}
			});
		}});
		$('.files').disableSelection();
	});
<?php $this->headScript()->captureEnd();?>

<div id="upload" ><span>Upload File</span></div><span id="status" ></span>

<ul id="files" class="files" >
	<li class="listtitle"><?php echo $this->t->_('FILE_DISP');?></li>
<?php 

if ($dp = opendir(APPLICATION_PATH.'/../upload/'.$this->user)) 
{
	while($file = readdir($dp)) {
		if (($file!=".")&&($file!="..")&&is_file(APPLICATION_PATH.'/../upload/'.$this->user.'/'.$file)&&!strstr($file, "thumb")&&($file!="prew.gif"))
		echo '
	<li class="success">
		<h4>'.$file.'</h4>
		'.$this->image('/upload/'.$this->user.'/thumb'.$file,$file,$file," "," ").$item_input.
		'</li>';
	}
}
else $this->log->debug("errore");
?>
</ul>
<ul class="files" id="framebox">
<li class="listtitle"><?php echo $this->t->_('FILE_ON_WORK');?></li>
</ul>

<div class="form">
	<div><input onclick="checkshow();" type="checkbox" checked="true" name="dimT" value="true" ><?php echo $this->t->_('DIMTOT');;?></div>
	<div>x <input name="x" type="number" min="32" value="150" size="4" maxlength="4" style="width:70px;">px</div>
	<div>y <input name="y" type="number" min="32" value="150" size="4" maxlength="4" style="width:70px;">px</div>
	<div><input name="prop" type="checkbox" checked="checked" value="true"><?php echo $this->t->_('PROP');?></div>
	<div><input checked="true" onclick="checkshow();" name="delayTot" type="checkbox" value="true"><?php echo $this->t->_('DELAY');?><input name="delayT" type="number" value="100" min="10" size="5" maxlength="5" style="width:70px;"></div>
	<div><input type="radio" checked="true" name="frameadd" value="2"><?php echo $this->t->_('REPLACE');?><input type="radio" name="frameadd" value="1"><?php echo $this->t->_('COMBINE');?></div>
	<div><button onclick="submit();"><?php echo $this->t->_('CREATE');?></button></div>
	
</div>
<ul id="trash"  class="files" title="<?php echo $this->t->_('TRASH_DESC');?>"></ul>