<?php 
$this->headScript()->captureStart();?>
function submitimg() {
	post={type:'scrool'}
	post.name=$('#framebox h4').text();
	submit('form',post,'<?php echo $this->url(array('controller'=>'make','action'=>'index'));?>',function(data) {
		//mess=data.mess.toString();
		if (data.bool) {
			post.type='processing';
			submit('form',post,'<?php echo $this->url(array('controller'=>'make','action'=>'index'));?>',function (data){
				$('<div><img src="<?php echo $this->baseUrl('/upload/'.$this->user);?>/temp/prew.gif"></div>').dialog({
					close:function(event,ui){$(this).dialog( "destroy" );}
				});
			});
		}
		else $('<div title="Error">fatal error </div>').dialog({ 
			buttons: [
			          {
			        	  text: "Ok",
			        	  click: function() { $(this).dialog("close"); }
			          }
			          ] 
		});
	});
}

$(function(){
	initUploader('<?php echo $this->url(array('controller'=>'uploader','action'=>'index'));?>','<?php echo $this->baseUrl('upload/'.$this->user);?>','');
	$('.files').sortable({
		connectWith: "ul",
		items:"li:not(.listtitle)",
		stop:function(){
			if ($('#framebox li').length>=2) {
				$('#files').sortable('option','connectWith','');
			}
			else {
				$('#files').sortable('option','connectWith','ul');
			}
			file=$('#trash h4').text();
			$('#trash li').remove();
			if (file.length) {
				$.ajax({
					url : '<?php echo $this->url(array('controller'=>'delete','action'=>'index'));?>',
					type: 'post',
					data : {'file':file}
				});
			}
		}
	});
	$('.files').disableSelection();
});
<?php $this->headScript()->captureEnd();?>

<div id="upload" ><span>Upload File</span></div><span id="status" ></span>

<ul id="files" class="files" >
	<li class="listtitle"><?php echo $this->t->_('FILE_DISP');?></li>
<?php 

if ($dp = @opendir(APPLICATION_PATH.'/../upload/'.$this->user)) 
{
	while($file = readdir($dp)) {
		if (($file!=".")&&($file!="..")&&is_file(APPLICATION_PATH.'/../upload/'.$this->user.'/'.$file)&&!strstr($file, "thumb")&&($file!="prew.gif"))
		echo '
	<li class="success">
		<h4>'.$file.'</h4>
		'.$this->image('/upload/'.$this->user.'/thumb'.$file,$file,$file).
		'</li>';
	}
}
else $this->log->notice("cartella ".APPLICATION_PATH.'/../upload/'.$this->user.'inesistente');
?>
</ul>
<ul class="files" id="framebox">
<li class="listtitle"><?php echo $this->t->_('FILE_ON_WORK');?></li>
</ul>

<div class="form">
	<div><?php echo $this->t->_('NofFrame');?><input type="number" min="2" max="50" name="nframe" value="2" ></div>
	<div><?php echo $this->t->_('DELAY');?><input name="delay" type="number" min="10" value="10" size="4" maxlength="4" style="width:70px;">cs</div>
	<div>
		<?php echo $this->t->_('DIMENTION');?> x <input name="x" type="number" min="32" value="150" size="4" maxlength="4" style="width:70px;">px
		y <input name="y" type="number" min="32" value="150" size="4" maxlength="4" style="width:70px;">px</div>
	<div>
		<?php echo $this->t->_('DIM_FRAME');?> x<input name="fx" type="number" min="32" value="150" size="4" maxlength="4" style="width:70px;">px
		y <input name="fy" type="number" min="32" value="150" size="4" maxlength="4" style="width:70px;">px
	</div>
	<div><input name="prop" type="checkbox" checked="checked" value="true"><?php echo $this->t->_('PROP');?></div>
	<div>
		<input name="scrollType" type="radio" value="v" checked="checked"/><?php echo $this->t->_('VERTICAL');?>
		<input name="scrollType" type="radio" value="h"/><?php echo $this->t->_('HORIZONTAL');?>
	</div>
	<div>
		<input name="start" type="radio" value="1" checked="checked"/><?php echo $this->t->_('TOP');?>/<?php echo $this->t->_('LEFT');?>
		<input name="start" type="radio" value="2" /><?php echo $this->t->_('BOTTOM');?>/<?php echo $this->t->_('RIGTH');?>
	</div>
	<div><input  name="fb" type="checkbox" value="true"><?php echo $this->t->_('FORWARD_BACK');?></div>
	<div class="beta"><input onclick="if ($(this).attr('checked')) $('#cf').show(); else $('#cf').hide()" name="custom" type="checkbox" value="true"><?php echo $this->t->_('CUSTOM_SCROLL');?></div>
	<div id="cf" style="display:none;">
		<div>x=Fx(t) <input name="fox" value="t" size="4" maxlength="4" style="width:70px;">px</div>
		<div>y=Fy(t) <input name="foy" value="t" size="4" maxlength="4" style="width:70px;">px</div>
	</div>
	<div><button onclick="submitimg();"><?php echo $this->t->_('CREATE');?></button></div>
</div>
<ul id="trash"  class="files" title="<?php echo $this->t->_('TRASH_DESC');?>"></ul>