<?php 
//init
$auth=Zend_Auth::getInstance();
$ua=new Zend_Http_UserAgent();
?>
<!DOCTYPE html>
<html>
	<head>
	<meta charset="UTF-8">
	<meta name="DESCRIPTION" content="<?php echo $this->t->_('DESCRIPTION');?>" />
	<meta name="KEYWORDS" content="gif,animate,tool,gratis" />
	<link rel="shortcut icon" href="<?php echo $this->baseUrl(); ?>/favicon.ico" />	
	<?php
	try {
		$device=$ua->getDevice();
		$mobile=$device->getFeature('is_mobile');
	} catch (Zend_Http_UserAgent_Exception $e) {
		$mobile=true;
	}
	echo $this->headLink()->prependStylesheet($this->baseUrl() . '/common/css/css.php'.($mobile? '?l=m' : ''));
	echo $this->headScript()->prependFile($this->baseUrl('/common/js/js.php'));
	?>
	  
	<script type="text/javascript">
	<!--
		$(function(){
			$('.beta').attr('title','<?php echo $this->t->_('NOTIMPL');?>');
		});
	//-->
	</script>
	<?php 
	$this->headTitle()->setSeparator(' - ');
	$this->headTitle('Nuvole libere');
	echo $this->headTitle();
	?>
	</head>
	<body>
		
		<div id="locale">language 
			<form action="<?php echo $this->url();?>">
				<select onchange="submit();" name="locale">
					<option value="browser">auto</option>
					<?php 
					foreach ($this->t->getList() as $key => $value) {
						echo '<option '.($_COOKIE['locale']==$key ? 'selected="selected"':'' ).' value="'.$key.'">'.$value.'</option>';
					}
					?>
				</select>
			</form>
		</div>
		<div id="container">
			<div id="header"></div>
	<?php 
	if ($this->logger) {
		$text="<ol>";
		foreach ($this->logger as $value) {
			$text.='<li class="priority'.$value['priority'].'">'.$value['timestamp'].' - '.$value['message'].' - '.$value['priorityName']."</li>";
		}
		$text.="</ol>";
		echo $this->template()->spoiler($text,false,'log');
	}
	//nav
	$nav['home']=array();
	
	?>
			<ul id="nav">
				<li><a href="<?php echo $this->url(array('controller'=>"index",'action'=>'index'));?>">Home</a></li>
		<?php 
		//user
		if ($auth->hasIdentity()) {
			echo '
				<li><a href="'.$this->url(array('controller'=>"login",'action'=>'logout')).'">logout</a></li>
				<li><a class="beta" href="'.$this->url(array('controller'=>"profile",'action'=>'index')).'">'.$this->t->_('PROFILE').'</a></li>';
		}
		else {
			echo '
				<li><a href="'.$this->url(array('controller'=>"login",'action'=>'index')).'">login</a></li>
				<li><a class="beta" href="'.$this->url(array('controller'=>"reg",'action'=>'index')).'">'.$this->t->_('REG').'</a></li>';	
		}
			/*
				<li><a href="<?php echo $this->url(array('controller'=>"create",'action'=>'index'));?>"><?php echo $this->t->_('CREATE');?></a></li>
				<li><a href="<?php echo $this->url(array('controller'=>"edit",'action'=>'index'));?>"><?php echo $this->t->_('EDIT');?></a></li>
			*/
			?></ul>
			<div id="content"><?php 
			echo $this->layout()->content; ?>
			</div>
			<div id="footer"><?php 
		if ($auth->hasIdentity()) {
			$user=$auth->getIdentity()->username;
			$role = Model_role::getRole();
		}
        else {
        	$user=Model_guest::getgid();
        	$role = 'guest';
        }
			echo "$role $user";?>
			</div>
		</div>
		
	</body>
</html>